name: flexicon
description: "Flex Icon from Streamlinehq"
version: 0.7.0
homepage: https://www.streamlinehq.com/icons/flex-line
repository: https://github.com/xkaper001/flexicon
issue_tracker: https://github.com/xkaper001/flexicon/issues
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
topics:
  - flutter
  - icon
  - icons
  - streamline
  - flexicon

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  fonts:
    - family: FlexRemix
      fonts:
        - asset: fonts/FlexRemix.ttf
    - family: FlexPop
      fonts:
        - asset: fonts/FlexPop.ttf
    - family: FlexFlat
      fonts:
        - asset: fonts/FlexFlat.ttf
    - family: FlexLine
      fonts:
        - asset: fonts/FlexLine.ttf
    - family: FlexNeon
      fonts:
        - asset: fonts/FlexNeon.ttf
    - family: FlexSolid
      fonts:
        - asset: fonts/FlexSolid.ttf
    - family: Gradient
      fonts:
        - asset: fonts/FlexGradient.ttf
